#!/usr/bin/env bash
#
# Print CPU utilization per core in a nice
# visual form from mpstat(1)
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 4/17/12

# Default number of columns to display
columns=80
# The character to use in the bar graphs
bar_character='|'
# Color output or not
color=true

#
# Display usage
#
usage() {
	cat <<-EOF
	Usage: ${0##*/} [ options ] [ <interval> [ <count> ] ]

	Print CPU utilization per core in a nice
	visual form from mpstat(1)

	Example Usage: ${0##*/} -c 30 -b '#' 1 5
	- Report for 5 times at 1 second intervals,
	  reserving 30 characters for the bar graph using # as
	  the graph character

	-b <char>    : Character to use for the bar graph
	-c <columns> : Number of columns to use for the bar graph
	-n           : Disable color output
	-h           : Print this help message

	EOF
}

#
# Load colors into variables
#
load_colors() {
	black=$(tput setaf 0)
	red=$(tput setaf 1)
	green=$(tput setaf 2)
	yellow=$(tput setaf 3)
	blue=$(tput setaf 4)
	magenta=$(tput setaf 5)
	cyan=$(tput setaf 6)
	white=$(tput setaf 7)
	bold=$(tput bold)
	reset=$(tput sgr0)
}


# Display bars for a given percent
#
# $1 = percentage
#
print_bars() {
	local perc=${1//%/}
	local decimal=$(bc <<< "scale=2; $perc / 100.0")
	local num_bars_dec=$(bc <<< "$columns * $decimal")
	local num_bars=${num_bars_dec%%.*}

	for ((i=1; i<=columns; i++)); do
		((i <= num_bars)) && echo -n "$bar_character" || echo -n " "
	done
	echo
}

#
# Main function
#
# Generate output and print it
#
main() {
	# Grab the out of prstat
	output=$(mpstat)

	# Loop the output of prstat and extract the meaninful fields
	first=true
	i=0
	while read CPU minf mjf xcal intr ithr csw icsw migr smtx srw syscl usr sys wt idl; do
		# Ignore the headers
		if $first; then
			first=false
			continue
		fi

		# Invert idle to get percent used
		perc_used[$i]=$(( 100 - idl ))
		(( i++ ))
	done <<< "$output"

	# Print the output
	for (( i=0 ; i < ${#perc_used[@]} ; i++ )) do
		perc_used_core=${perc_used[$i]}
		printf "${green}CPU %2d: ${bold}${blue}[${reset}${red}%s${bold}${blue}]${reset} ${cyan}%3d%%\n" \
			"$i" "$(print_bars "$perc_used_core")" "$perc_used_core"
	done

	# Reset all colors
	echo -n "$reset"
}

# Get command line options
while getopts "b:c:nh" options; do
	case "$options" in
		b) bar_character=$OPTARG;;
		c) columns=$OPTARG;;
		n) color=false;;
		h) usage >&2; exit 0;;
		*) usage >&2; exit 1;;
	esac
done
shift $(($OPTIND-1))

# Check if colors should be loaded
"$color" && load_colors

# Check if an interval was given
if [[ -n "$1" ]]; then
	interval=$1
	# Check if a count was given
	if [[ -n "$2" ]]; then
		i=0
		count=$2
	fi

	# Clear the screen and run the loop
	while true; do
		output=$(main; date)
		clear
		echo "$output"
		# If counting, inecrement the counter and exit if over $count
		if [[ -n "$count" ]]; then
			((i++))
			if ((i >= count)); then
				exit 0
			fi
		fi
		sleep "$interval"
	done
fi
main
