#!/usr/bin/env bash
#
# Print CPU utilization per core in a nice
# visual form from mpstat(1M)
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: 4/17/12

# Source the lib
if [[ -z "$lib_is_loaded" ]]; then
	. lib/visusage.bash || exit 1
fi

#
# Display usage
#
usage() {
	cat <<-EOF
	Usage: ${0##*/} [ options ] [ <interval> [ <count> ] ]

	Print CPU utilization per core in a nice
	visual form from mpstat(1M)

	Example Usage: ${0##*/} -c 30 -b '#' 1 5
	- Report for 5 times at 1 second intervals,
	  reserving 30 characters for the bar graph using # as
	  the graph character

	-b <char>    : Character to use for the bar graph
	-c <columns> : Number of columns to use for the bar graph
	-n           : Disable color output
	-h           : Print this help message

	EOF
}

#
# Generate the output
#
gen_output() {
	# Print the output/flush
	for (( i=0 ; i < ${#perc_used[@]} ; i++ )) do
		perc_used_usr=${perc_usr[$i]}
		perc_used_sys=${perc_sys[$i]}
		perc_used_core=${perc_used[$i]}
		bars=$(echo -n "$green"; print_bars "$perc_used_usr"; echo -n "$red"; print_bars "$perc_used_sys")
		"$color" && col=$(( columns + ${#green} + ${#red} )) || col=$columns
		printf "${green}CPU %2d: ${bold}${blue}[${reset}%-*s${bold}${blue}]${reset} ${cyan}%3d%%\n" \
			"$i" "$col" "$bars" "$perc_used_core"
	done
	# Reset
	echo -n "$reset"
}

#
# Main function
#
# Generate output and print it
#
main() {
	# Loop the output of mpstat(1M) and extract the meaninful fields
	first=true
	i=0
	while read CPU minf mjf xcal intr ithr csw icsw migr smtx srw syscl usr sys wt idl; do
		# Ignore the headers
		if $first; then
			first=false
			continue
		fi

		# Invert idle to get percent used
		perc_usr[$i]=$usr
		perc_sys[$i]=$sys
		perc_used[$i]=$(( 100 - idl ))
		(( i++ ))

		if (( i >= corecount )); then
			output=$(gen_output; date;)
			[[ -n "$1" ]] && clear

			echo "$output"

			first=true
			i=0
		fi
	done < <(mpstat "$@")
}

# Get command line options
while getopts "b:c:nh" options; do
	case "$options" in
		b) bar_character=$OPTARG;;
		c) columns=$OPTARG;;
		n) color=false;;
		h) usage >&2; exit 0;;
		*) usage >&2; exit 1;;
	esac
done
shift $(($OPTIND-1))

# Check if colors should be loaded
"$color" && load_colors

# Start it
main "$@"
